### ISSUE TITLE
This site is incomplete and having issue like responsiveness and etc.

### ISSUE THREAD

**Issue by Malik-Saifullah** [qaxim/cssfront#1]
Qasim Bhai I see some issues in your sites like responsiveness and missing links or pages.
![CSSFront Components - Google Chrome 16_11_2019 2_52_22 pm](https://user-images.githubusercontent.com/43086869/68991540-b2b17880-0881-11ea-841f-7ae8415ed9ba.png)
![CSSFront Components - Google Chrome 16_11_2019 2_52_41 pm](https://user-images.githubusercontent.com/43086869/68991541-b2b17880-0881-11ea-9906-707061e6f7d9.png)
![d7db0ac4-eb88-4ac3-b2d7-1dd53f5682a4](https://user-images.githubusercontent.com/43086869/68991542-b2b17880-0881-11ea-9e88-53fc3e486437.png)
![CSSFront Components - Google Chrome 16_11_2019 2_46_31 pm](https://user-images.githubusercontent.com/43086869/68991543-b34a0f00-0881-11ea-886d-505186ae44a5.png)
![CSSFront Components - Google Chrome 16_11_2019 2_49_19 pm](https://user-images.githubusercontent.com/43086869/68991544-b34a0f00-0881-11ea-89df-65e14d92c124.png)
![CSSFront Components - Google Chrome 16_11_2019 2_50_34 pm](https://user-images.githubusercontent.com/43086869/68991545-b3e2a580-0881-11ea-92e1-31f82945a4f2.png)
![CSSFront Components - Google Chrome 16_11_2019 2_51_21 pm](https://user-images.githubusercontent.com/43086869/68991546-b3e2a580-0881-11ea-9be0-8acae9ceb505.png)

**Comment by codeqasim** [comment]
Thanks I'm writing entire CSS again with new design.
